name: Question
description: Ask a question about the SDK
title: '[Question]: '
labels: ['question', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Please provide context and any relevant code or logs.
