name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm ci --no-audit
      - name: Run lint
        run: npm run lint
      - name: Run typecheck
        run: npm run typecheck
